### ISSUE TITLE
[Feature][Plugin] Refactor seatunnel-connector structure

### ISSUE THREAD

**Issue by zixi0825** [apache/incubator-seatunnel#824]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The sink-plugin-module and source-plugin-module under seatunnel-connectors  should be merge into a connector module
- refactor before :

![1639813070(1)](https://user-images.githubusercontent.com/10829956/146633503-a322227b-72a2-43ce-9f08-7493618ccaf9.png)
- refactor after :

![1639813318(1)](https://user-images.githubusercontent.com/10829956/146633604-6aa12806-886a-4025-bd5e-aacec1203f30.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by garyelephant** [comment]
LGTM

**Comment by garyelephant** [comment]
From my view, I think we can:

* merge source and sink to a combined connector, because the source and sink of a specific storage probably dependent on  some common libraries

* keep spark and flink connectors separately because we may directly use connectors from spark, flink if possible, and users of one of spark or flink connectors do not intend to load dependencies from both spark and flink.

**Comment by CalvinKirs** [comment]
done
